module Code0
  module Identities
    module Provider
      class BaseOauth
        attr_reader config_loader: Proc | Hash[Symbol, any]

        def initialize: (config_loader: Proc | Hash[Symbol, any]) -> void

        def authorization_url: () -> String

        def token_url: () -> String

        def user_details_url: () -> String

        def config: () -> Hash[Symbol, any]

        def create_identity: (response: Net::HTTPResponse, token: String, token_type: String) -> Identity
      end
    end
  end
end
