module Code0
  module Identities
    module Provider
      class Gitlab < BaseOauth
        def base_url: () -> String

        def token_url: () -> ::String

        def token_payload: (code: String) -> { code: String, grant_type: "authorization_code", redirect_uri: String, client_id: String, client_secret: String }

        def user_details_url: () -> ::String

        def authorization_url: () -> String

        def create_identity: (response: Net::HTTPResponse) -> Identity
      end
    end
  end
end
