module Code0
  module Identities
    module Provider
      class Saml
        def authorization_url: () -> String

        def config_attributes: -> { optional: Array[Symbol], required: Array[Symbol] }

        def load_identity: (Hash[Symbol, any]) -> Identity
      end
    end
  end
end
