module Code0
  module Identities
    module Provider
      class Saml
        def authorization_url: () -> String

        def validate_config!: -> void

        def load_identity: (Hash[Symbol, any]) -> Identity
      end
    end
  end
end
